### ISSUE TITLE
sparkfun logo doesn't light up

### ISSUE THREAD

**Issue by robz** [ut-ras/ras_site_old#10]
When hovering over the sparkfun logo, the fire doesn't turn red.

**Comment by cmonr** [comment]
FWIW, TI doesn't either.

**Comment by sissyliberation** [comment]
This is not an error. Both of those images are black. Change the images to a non-black image if you want the hover action to do anything.

**Comment by dteal** [comment]
Also, it appears SparkFun isn't a sponsor anymore. :(
