### ISSUE TITLE
Add javascript to create mail-to links in the contacts page.

### ISSUE THREAD

**Issue by JennDahm** [ut-ras/ras_site_old#16]
To avoid site scrapers picking up our public emails, we write them in an unconventional format (`name (at) url`) and don't include mail-to links with them. However, this is inconvenient for our actual users. Since scrapers are unlikely to run javascript, we can write a script to find these addresses and generate mail-to links from them without seriously increasing our risk of spam.

Some suggestions:
- Don't include the addresses themselves in the javascript source anywhere -- that defeats the purpose.
- It may be useful to surround the addresses with an appropriate tag and give the tag a descriptive class.
- Bonus: Have the script run on other pages as well.

**Comment by dteal** [comment]
Done in bootstrap branch.
