### ISSUE TITLE
slides link broken

### ISSUE THREAD

**Issue by robz** [ut-ras/ras_site_old#2]
The engineering process slides link at the bottom of the media page appears to redirect to the media page.

**Comment by sidrdesai** [comment]
I don't know where the actual powerpoint is. Can someone send me a link to that?

**Comment by sissyliberation** [comment]
Ah, Rachel should have them. We did that presentation together; I sent her the slides for my part, and she put the final version together. Ask her for them.

**Comment by RaeSmith1331** [comment]
What slides do you need?

**Comment by sissyliberation** [comment]
The powerpoint slides for the Engineering Process presentation you and I did together as a RAS tech-talk. 

Go to http://ras.ece.utexas.edu/media.html and scroll down to the bottom of the page, for reference. 
If you don't recall, it's the talk where we did the 6-3-5 Brainwriting exercise with the students.

**Comment by RaeSmith1331** [comment]
Here it is.

On Thu, Jan 16, 2014 at 2:04 PM, Yves Courtois notifications@github.comwrote:

> The powerpoint slides for the Engineering Process presentation you and I
> did together as a RAS tech-talk.
> 
> Go to http://ras.ece.utexas.edu/media.html and scroll down to the bottom
> of the page, for reference.
> If you don't recall, it's the talk where we did the 6-3-5 Brainwriting
> exercise with the students.
> 
> —
> Reply to this email directly or view it on GitHubhttps://github.com/ut-ras/ras_site/issues/2#issuecomment-32529748
> .

## 

_Rachel Smith_
Undergraduate Research Assistant, ReNeu Robotics Lab
Electrical and Computer Engineering, 2015
The University of Texas at Austin

**Comment by sidrdesai** [comment]
I don't see anything. Am I missing something?

**Comment by sissyliberation** [comment]
I second what @sidrdesai said.

**Comment by RaeSmith1331** [comment]
I attached it.

**Comment by sissyliberation** [comment]
GitHub does not allow you to attach documents if you are replying through your email notifications. 
Please email ras_president@utlists.utexas.edu the slides. 

@robz make sure they get to @sidrdesai after so it can be put in the server.

**Comment by sissyliberation** [comment]
@RachSmith here you'll see that email attachments are ignored: https://github.com/blog/811-reply-to-comments-from-email

**Comment by robz** [comment]
She emailed it to me, and I uploaded it to RAS's google drive: https://drive.google.com/file/d/0B0xTWxHBRZ1cYmpfNmxlT2lJMkE/edit?usp=sharing

**Comment by robz** [comment]
the link is still broken...

**Comment by dteal** [comment]
...and, the link has been removed. Closed for now.
