### ISSUE TITLE
Update Committee About Pages

### ISSUE THREAD

**Issue by dimembermatt** [ut-ras/ras_site_old#60]
Main About page should add:
- [x] Robomaster

About pages should be updated with any new information, descriptions, etc:
- [x] Robotathon
- [x] Demobots
- [x] IGVC
- [x] Robomaster
- [x] Micromouse

Should be updated to reflect that they've been discontinued:
- [x] Region 5
- [x] Robosub

**Comment by dimembermatt** [comment]
Any updates from committee heads on this?

**Comment by RosannaR** [comment]
I have set a deadline (May 23rd) for the committee heads to send me any updates they want to add, so far only Caitlin has gotten back to me.
