### ISSUE TITLE
About Page

### ISSUE THREAD

**Issue by SaltyNotes** [ut-ras/ras_site_old#8]
on the about page the description for mercury is "This is a description of the competition". Can you change it to "Long distance remote controlled robotics challenge" or something? 

Also can you remove the special events stuff cause it doesn't pertain to this semester's events. Thanks!

**Comment by JennDahm** [comment]
This issue was created over two years ago. Since then this problem has been fixed, and we've just recently removed Mercury from our About page entirely. As such, I've closed the issue.
